### ISSUE TITLE
how to play ai?

### ISSUE THREAD

**Issue by cloudjanak** [connorlay/scrabble#1]
can i get all possiable moves that can be played on the current board with starting position and direction
for example you can check below web-site
http://www.lexicalwordfinder.com/?game=Words_With_Friends&layout=1&tiles=gtsfsdf&board=----------------------------------------------------------------------------------------------------------------hello------------------------------------------------------------------------------------------------------------&lexicon=wwf

**Comment by connorlay** [comment]
The findBestMove and makeMove methods in Game.java used by the AI perform the following:
1. For each tile already on the board, make a list of all anagrams using the tiles in the AI's tray and the selected tile on the board.
2. For each word in the list of anagrams, place tiles on the board to spell the word and record the resulting score. This allows the AI to take advantage of score modifiers.
3. Choose the word placement that scores the most points.

To calculate the score of a given word any crosswords must be included. That way the AI can spell multiple words to score more points. Modifying findBestMove and makeMove to take a specific direction and starting tile and print out each word placed would get you a Scrabble solver.

**Comment by cloudjanak** [comment]
can you add one example for that?
